/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.banhang;

import dao.HoaDonDAO;
import dao.ThongKeDAO;
import helper.DateHelper;
import helper.ShareHelper;
import java.awt.Color;
import java.awt.Dimension;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class TongKetCuoiNgayJFrame extends javax.swing.JFrame {

    /**
     * Creates new form TongKetCuoiNgayJFrame
     */
    public TongKetCuoiNgayJFrame() {
        initComponents();
        this.setSize(530,600);
        this.setMinimumSize(new Dimension(530, 600));
        this.setMaximumSize(new Dimension(530, 600));
        this.getContentPane().setBackground(Color.white);
        setResizable(false);
        setLocationRelativeTo(null);
        hienThongTin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_NgayTongKet = new javax.swing.JLabel();
        lbl_NhanVien = new javax.swing.JLabel();
        lbl_DoanhThu = new javax.swing.JLabel();
        lbl_SoLuotKhach = new javax.swing.JLabel();
        txt_DoanhThu = new javax.swing.JTextField();
        txt_SoLuotKhach = new javax.swing.JTextField();
        lbl_SanPhamBanRa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_TongKetSanPhamBanRa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TỔNG KẾT CUỐI NGÀY");

        lbl_NgayTongKet.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_NgayTongKet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_NgayTongKet.setText("Ngày dd/MM/yyyy hh:mm:ss");

        lbl_NhanVien.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lbl_NhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_NhanVien.setText("Nhân viên: ..................");

        lbl_DoanhThu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_DoanhThu.setText("Doanh thu");

        lbl_SoLuotKhach.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_SoLuotKhach.setText("Số lượt khách");

        txt_DoanhThu.setEditable(false);
        txt_DoanhThu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_DoanhThu.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txt_SoLuotKhach.setEditable(false);
        txt_SoLuotKhach.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_SoLuotKhach.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lbl_SanPhamBanRa.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbl_SanPhamBanRa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_SanPhamBanRa.setText("SẢN PHẨM BÁN RA");

        tbl_TongKetSanPhamBanRa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbl_TongKetSanPhamBanRa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên nhóm hàng", "Số lượng", "Giá trị"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_TongKetSanPhamBanRa.setRowHeight(35);
        tbl_TongKetSanPhamBanRa.setRowMargin(3);
        jScrollPane1.setViewportView(tbl_TongKetSanPhamBanRa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_SoLuotKhach)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(txt_SoLuotKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_DoanhThu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_DoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_NgayTongKet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_NhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_SanPhamBanRa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbl_NgayTongKet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_NhanVien)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_DoanhThu)
                    .addComponent(txt_DoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_SoLuotKhach)
                    .addComponent(txt_SoLuotKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(lbl_SanPhamBanRa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TongKetCuoiNgayJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TongKetCuoiNgayJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TongKetCuoiNgayJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TongKetCuoiNgayJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TongKetCuoiNgayJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_DoanhThu;
    private javax.swing.JLabel lbl_NgayTongKet;
    private javax.swing.JLabel lbl_NhanVien;
    private javax.swing.JLabel lbl_SanPhamBanRa;
    private javax.swing.JLabel lbl_SoLuotKhach;
    private javax.swing.JTable tbl_TongKetSanPhamBanRa;
    private javax.swing.JTextField txt_DoanhThu;
    private javax.swing.JTextField txt_SoLuotKhach;
    // End of variables declaration//GEN-END:variables
    
    HoaDonDAO HoaDonDAO = new HoaDonDAO();
    ThongKeDAO ThongKeDAO = new ThongKeDAO();
    
    /*
     * Hàm hiển thị các thông tin
     */
    void hienThongTin(){
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
            String NgayTongKet = sdf.format(DateHelper.now());
            String TenNhanVien = ShareHelper.NguoiDung.getHoTen();
            lbl_NgayTongKet.setText(NgayTongKet);
            lbl_NhanVien.setText("Nhân viên: " + TenNhanVien);
            int SoLuotKhach = HoaDonDAO.demHoaDonTrongNgay(ShareHelper.NguoiDung.getTenDangNhap());
            txt_SoLuotKhach.setText(SoLuotKhach + "");
            float DoanhThu = HoaDonDAO.tinhDoanhThuTrongNgay(ShareHelper.NguoiDung.getTenDangNhap());
            txt_DoanhThu.setText(DoanhThu + "");
            doThongTinTongKet();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Có lỗi: " + e.toString());
        }
    }
    
    /*
     * Hàm đổ thông tin vào tbl_TongKetSanPhamBanRa
     */
    void doThongTinTongKet() throws SQLException{
        String MaNhanVien = ShareHelper.NguoiDung.getTenDangNhap();
        DefaultTableModel dtm = (DefaultTableModel) tbl_TongKetSanPhamBanRa.getModel();
        dtm.setRowCount(0);
        List<Object[]> list = ThongKeDAO.ThongKeCuoiNgay(MaNhanVien);
        for(Object obj[] : list){
            dtm.addRow(obj);
        }
    }
}
