/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.quanly.nhanvien;

import dao.NguoiDungDAO;
import dao.ThongKeDAO;
import helper.DialogHelper;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.NguoiDung;

/**
 *
 * @author Admin
 */
public class DanhSachNhanVienJFrame extends javax.swing.JFrame {

    /**
     * Creates new form DanhSachNhanVienJFrame
     */
    public DanhSachNhanVienJFrame() {
        initComponents();
        inIt();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btg_TrangThai = new javax.swing.ButtonGroup();
        pnl_CotPhai = new javax.swing.JPanel();
        lbl_TieuDe = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_DanhSachNhanVien = new javax.swing.JTable();
        btn_ThemMoi = new javax.swing.JButton();
        pnl_CotTrai = new javax.swing.JPanel();
        lbl_TimKiem = new javax.swing.JLabel();
        txt_TimTheoMaTenSDT = new javax.swing.JTextField();
        rad_TatCa = new javax.swing.JRadioButton();
        rad_DangHoatDong = new javax.swing.JRadioButton();
        rad_NgungHoatDong = new javax.swing.JRadioButton();
        lbl_TrangThai = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DANH SÁCH NHÂN VIÊN");
        setResizable(false);

        lbl_TieuDe.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_TieuDe.setForeground(new java.awt.Color(51, 51, 255));
        lbl_TieuDe.setText("DANH SÁCH NHÂN VIÊN");

        tbl_DanhSachNhanVien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbl_DanhSachNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Vai trò", "Điện thoại", "Doanh thu", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_DanhSachNhanVien.setRowHeight(35);
        tbl_DanhSachNhanVien.setRowMargin(3);
        tbl_DanhSachNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_DanhSachNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_DanhSachNhanVien);

        btn_ThemMoi.setBackground(new java.awt.Color(255, 51, 0));
        btn_ThemMoi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_ThemMoi.setForeground(new java.awt.Color(255, 255, 255));
        btn_ThemMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/themKhachHang.png"))); // NOI18N
        btn_ThemMoi.setText("THÊM MỚI");
        btn_ThemMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ThemMoiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ThemMoiMouseExited(evt);
            }
        });
        btn_ThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_CotPhaiLayout = new javax.swing.GroupLayout(pnl_CotPhai);
        pnl_CotPhai.setLayout(pnl_CotPhaiLayout);
        pnl_CotPhaiLayout.setHorizontalGroup(
            pnl_CotPhaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_CotPhaiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_CotPhaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnl_CotPhaiLayout.createSequentialGroup()
                        .addComponent(lbl_TieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                        .addComponent(btn_ThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnl_CotPhaiLayout.setVerticalGroup(
            pnl_CotPhaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_CotPhaiLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnl_CotPhaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_ThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_TieuDe))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pnl_CotTrai.setBackground(new java.awt.Color(255, 255, 255));

        lbl_TimKiem.setBackground(new java.awt.Color(102, 102, 255));
        lbl_TimKiem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_TimKiem.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TimKiem.setText("   TÌM KIẾM");
        lbl_TimKiem.setOpaque(true);

        txt_TimTheoMaTenSDT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_TimTheoMaTenSDT.setForeground(new java.awt.Color(204, 204, 204));
        txt_TimTheoMaTenSDT.setText("Tìm kiếm theo mã, tên, SĐT");
        txt_TimTheoMaTenSDT.setToolTipText("");
        txt_TimTheoMaTenSDT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_TimTheoMaTenSDTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_TimTheoMaTenSDTFocusLost(evt);
            }
        });
        txt_TimTheoMaTenSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TimTheoMaTenSDTActionPerformed(evt);
            }
        });
        txt_TimTheoMaTenSDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_TimTheoMaTenSDTKeyReleased(evt);
            }
        });

        rad_TatCa.setBackground(new java.awt.Color(255, 255, 255));
        btg_TrangThai.add(rad_TatCa);
        rad_TatCa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rad_TatCa.setSelected(true);
        rad_TatCa.setText("Tất cả");
        rad_TatCa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rad_TatCaItemStateChanged(evt);
            }
        });
        rad_TatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad_TatCaActionPerformed(evt);
            }
        });

        rad_DangHoatDong.setBackground(new java.awt.Color(255, 255, 255));
        btg_TrangThai.add(rad_DangHoatDong);
        rad_DangHoatDong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rad_DangHoatDong.setText("Đang hoạt động");
        rad_DangHoatDong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rad_DangHoatDongItemStateChanged(evt);
            }
        });

        rad_NgungHoatDong.setBackground(new java.awt.Color(255, 255, 255));
        btg_TrangThai.add(rad_NgungHoatDong);
        rad_NgungHoatDong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rad_NgungHoatDong.setText("Ngưng hoạt động");
        rad_NgungHoatDong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rad_NgungHoatDongItemStateChanged(evt);
            }
        });

        lbl_TrangThai.setBackground(new java.awt.Color(102, 102, 255));
        lbl_TrangThai.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_TrangThai.setForeground(new java.awt.Color(255, 255, 255));
        lbl_TrangThai.setText("   TRẠNG THÁI");
        lbl_TrangThai.setOpaque(true);

        javax.swing.GroupLayout pnl_CotTraiLayout = new javax.swing.GroupLayout(pnl_CotTrai);
        pnl_CotTrai.setLayout(pnl_CotTraiLayout);
        pnl_CotTraiLayout.setHorizontalGroup(
            pnl_CotTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_TimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_TrangThai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl_CotTraiLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnl_CotTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_TimTheoMaTenSDT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                    .addGroup(pnl_CotTraiLayout.createSequentialGroup()
                        .addGroup(pnl_CotTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rad_TatCa)
                            .addComponent(rad_DangHoatDong)
                            .addComponent(rad_NgungHoatDong))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
        );
        pnl_CotTraiLayout.setVerticalGroup(
            pnl_CotTraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_CotTraiLayout.createSequentialGroup()
                .addComponent(lbl_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_TimTheoMaTenSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(lbl_TrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rad_TatCa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rad_DangHoatDong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rad_NgungHoatDong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_CotTrai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnl_CotPhai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_CotTrai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_CotPhai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_TimTheoMaTenSDTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_TimTheoMaTenSDTFocusGained
        if (txt_TimTheoMaTenSDT.getText().equals("Tìm kiếm theo mã, tên, SĐT")) {
            txt_TimTheoMaTenSDT.setText("");
            txt_TimTheoMaTenSDT.setForeground(new Color(0, 0, 0));
        }
        rad_TatCa.setSelected(true);
    }//GEN-LAST:event_txt_TimTheoMaTenSDTFocusGained

    private void txt_TimTheoMaTenSDTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_TimTheoMaTenSDTFocusLost
        if (txt_TimTheoMaTenSDT.getText().equals("")) {
            txt_TimTheoMaTenSDT.setText("Tìm kiếm theo mã, tên, SĐT");
            txt_TimTheoMaTenSDT.setForeground(new Color(204, 204, 204));
        }
    }//GEN-LAST:event_txt_TimTheoMaTenSDTFocusLost

    private void txt_TimTheoMaTenSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TimTheoMaTenSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TimTheoMaTenSDTActionPerformed

    private void btn_ThemMoiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThemMoiMouseEntered
        // TODO add your handling code here:
        btn_ThemMoi.setBackground(Color.yellow);
        btn_ThemMoi.setForeground(Color.blue);
        btn_ThemMoi.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_ThemMoiMouseEntered

    private void btn_ThemMoiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThemMoiMouseExited
        // TODO add your handling code here:
        btn_ThemMoi.setBackground(new Color(255, 51, 0));
        btn_ThemMoi.setForeground(Color.white);
    }//GEN-LAST:event_btn_ThemMoiMouseExited

    private void btn_ThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemMoiActionPerformed
        // TODO add your handling code here:
        new ThemMoiNhanVienJFrame().setVisible(true);
    }//GEN-LAST:event_btn_ThemMoiActionPerformed

    private void rad_TatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_TatCaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rad_TatCaActionPerformed

    private void txt_TimTheoMaTenSDTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TimTheoMaTenSDTKeyReleased
        // TODO add your handling code here:
        timTongHop();
    }//GEN-LAST:event_txt_TimTheoMaTenSDTKeyReleased

    private void rad_TatCaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rad_TatCaItemStateChanged
        // TODO add your handling code here:
        capnhatDuLieu();
    }//GEN-LAST:event_rad_TatCaItemStateChanged

    private void rad_DangHoatDongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rad_DangHoatDongItemStateChanged
        // TODO add your handling code here:
        locTheoTrangThai(1);
    }//GEN-LAST:event_rad_DangHoatDongItemStateChanged

    private void rad_NgungHoatDongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rad_NgungHoatDongItemStateChanged
        // TODO add your handling code here:
        locTheoTrangThai(0);
    }//GEN-LAST:event_rad_NgungHoatDongItemStateChanged

    private void tbl_DanhSachNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_DanhSachNhanVienMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            capnhatNhanVien();
        }
    }//GEN-LAST:event_tbl_DanhSachNhanVienMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DanhSachNhanVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DanhSachNhanVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DanhSachNhanVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DanhSachNhanVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DanhSachNhanVienJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btg_TrangThai;
    private javax.swing.JButton btn_ThemMoi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_TieuDe;
    private javax.swing.JLabel lbl_TimKiem;
    private javax.swing.JLabel lbl_TrangThai;
    private javax.swing.JPanel pnl_CotPhai;
    private javax.swing.JPanel pnl_CotTrai;
    private javax.swing.JRadioButton rad_DangHoatDong;
    private javax.swing.JRadioButton rad_NgungHoatDong;
    private javax.swing.JRadioButton rad_TatCa;
    private javax.swing.JTable tbl_DanhSachNhanVien;
    private javax.swing.JTextField txt_TimTheoMaTenSDT;
    // End of variables declaration//GEN-END:variables

    NguoiDungDAO NguoiDungDAO = new NguoiDungDAO();
    ThongKeDAO ThongKeDAO = new ThongKeDAO();

    // Định dạng hiển thị số tiền:
    DecimalFormat dcf = new DecimalFormat("###,###,###.###");

    /*
     * Hàm khởi tạo các giá trị ban đầu cho JFrame
     */
    void inIt() {
        this.setSize(1366, 768);
        this.setMinimumSize(new Dimension(1366, 768));
        this.setMaximumSize(new Dimension(1366, 768));
        setResizable(false);
        setLocationRelativeTo(null);
        capnhatDuLieu();
    }

    /*
     * Hàm cập nhật dữ liệu NguoiDung
     */
    void capnhatDuLieu() {
        try {
            List<NguoiDung> listND = NguoiDungDAO.select();
            doDuLieuVaoBang(listND);
        } catch (Exception e) {
            DialogHelper.alert(this, "Có lỗi: " + e.toString());
        }
    }

    /*
     * Hàm đổ dữ liệu vào bảng
     */
    void doDuLieuVaoBang(List<NguoiDung> listND) throws SQLException {
        DefaultTableModel dtm = (DefaultTableModel) tbl_DanhSachNhanVien.getModel();
        dtm.setRowCount(0);
        for (NguoiDung ND : listND) {
            double DoanhThu = ThongKeDAO.tinhDoanhThuNV(ND.getTenDangNhap());
            Object[] row = {ND.getTenDangNhap(),
                ND.getHoTen(),
                ND.getVaiTro() == 1 ? "Quản lý" : (ND.getVaiTro() == 0 ? "Nhân viên" : "Thủ kho"),
                ND.getDienThoai(),
                dcf.format(DoanhThu),
                ND.getTrangThai() ? "Đang hoạt động" : "Ngưng hoạt động"
            };
            dtm.addRow(row);
        }
    }

    /*
     * Hàm tìm tổng hợp theo mã, tên, SĐT
     */
    void timTongHop() {
        String ChuoiTimKiem = txt_TimTheoMaTenSDT.getText();
        if (!ChuoiTimKiem.isEmpty()) {
            try {
                List<NguoiDung> listND = NguoiDungDAO.timTheoMaTenSDT(ChuoiTimKiem);
                doDuLieuVaoBang(listND);
            } catch (Exception e) {
                DialogHelper.alert(this, "Có lỗi: " + e.toString());
            }
        } else {
            capnhatDuLieu();
        }
    }

    /*
     * Hàm lọc theo trạng thái
     */
    void locTheoTrangThai(int i) {
        try {
            List<NguoiDung> listND;
            if (i == 1) {
                listND = NguoiDungDAO.locTheoTrangThai(1);
            } else {
                listND = NguoiDungDAO.locTheoTrangThai(0);
            }
            doDuLieuVaoBang(listND);
        } catch (Exception e) {
            DialogHelper.alert(this, "Có lỗi: " + e.toString());
        }
    }

    /*
     * Hàm gọi frame cập nhật nhân viên
     */
    void capnhatNhanVien() {
        int index = tbl_DanhSachNhanVien.getSelectedRow();
        String TenDangNhap = tbl_DanhSachNhanVien.getValueAt(index, 0).toString();
        try {
            NguoiDung ND = NguoiDungDAO.timTenDangNhap(TenDangNhap);
            new CapNhatNhanVienJFrame(ND).setVisible(true);
        } catch (Exception e) {
            DialogHelper.alert(this, "Có lỗi: " + e.toString());
        }

    }
}
