/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.chung;

import dao.NguoiDungDAO;
import helper.DateHelper;
import helper.DialogHelper;
import helper.ShareHelper;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.swing.JTextField;

/**
 *
 * @author Administrator
 */
public class ThongTinTaiKhoanJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ThongTinTaiKhoanJFrame
     */
    public ThongTinTaiKhoanJFrame() {
        initComponents();
        this.setSize(530,550);
        this.setMinimumSize(new Dimension(530, 550));
        this.setMaximumSize(new Dimension(530, 550));
        setResizable(false);
        setLocationRelativeTo(null);
        hienThongTin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btg_GioiTinh = new javax.swing.ButtonGroup();
        lbl_TenDangNhap = new javax.swing.JLabel();
        txt_TenDangNhap = new javax.swing.JTextField();
        lbl_HoTen = new javax.swing.JLabel();
        txt_HoTen = new javax.swing.JTextField();
        lbl_DienThoai = new javax.swing.JLabel();
        txt_DienThoai = new javax.swing.JTextField();
        lbl_GioiTinh = new javax.swing.JLabel();
        rad_Nam = new javax.swing.JRadioButton();
        rad_Nu = new javax.swing.JRadioButton();
        txt_Email = new javax.swing.JTextField();
        lbl_Email = new javax.swing.JLabel();
        lbl_NgaySinh = new javax.swing.JLabel();
        dat_NgaySinh = new com.toedter.calendar.JDateChooser();
        lbl_DiaChi = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txa_DiaChi = new javax.swing.JTextArea();
        lbl_MatKhauHienTai = new javax.swing.JLabel();
        lbl_MatKhauMoi = new javax.swing.JLabel();
        txt_MatKhauHienTai = new javax.swing.JPasswordField();
        txt_MatKhauMoi = new javax.swing.JPasswordField();
        pnl_Button = new javax.swing.JPanel();
        btn_Huy = new javax.swing.JButton();
        btn_CapNhat = new javax.swing.JButton();
        chk_CapNhatMatKhau = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("THÔNG TIN TÀI KHOẢN");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(530, 550));
        setMinimumSize(new java.awt.Dimension(530, 550));
        setResizable(false);
        setSize(new java.awt.Dimension(530, 550));

        lbl_TenDangNhap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_TenDangNhap.setForeground(new java.awt.Color(0, 0, 153));
        lbl_TenDangNhap.setText("Tên đăng nhâp");

        txt_TenDangNhap.setEditable(false);
        txt_TenDangNhap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbl_HoTen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_HoTen.setForeground(new java.awt.Color(0, 0, 153));
        lbl_HoTen.setText("Họ tên");

        txt_HoTen.setEditable(false);
        txt_HoTen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lbl_DienThoai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_DienThoai.setForeground(new java.awt.Color(0, 0, 153));
        lbl_DienThoai.setText("Điện thoại");

        txt_DienThoai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_DienThoai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_DienThoaiFocusLost(evt);
            }
        });
        txt_DienThoai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_DienThoaiKeyTyped(evt);
            }
        });

        lbl_GioiTinh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_GioiTinh.setForeground(new java.awt.Color(0, 0, 153));
        lbl_GioiTinh.setText("Giới tính");

        btg_GioiTinh.add(rad_Nam);
        rad_Nam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rad_Nam.setForeground(new java.awt.Color(0, 0, 153));
        rad_Nam.setSelected(true);
        rad_Nam.setText("Nam");

        btg_GioiTinh.add(rad_Nu);
        rad_Nu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rad_Nu.setForeground(new java.awt.Color(0, 0, 153));
        rad_Nu.setText("Nữ");

        txt_Email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_Email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_EmailFocusLost(evt);
            }
        });

        lbl_Email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Email.setForeground(new java.awt.Color(0, 0, 153));
        lbl_Email.setText("Email");

        lbl_NgaySinh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_NgaySinh.setForeground(new java.awt.Color(0, 0, 153));
        lbl_NgaySinh.setText("Ngày sinh");

        dat_NgaySinh.setDateFormatString("dd/MM/yyyy");
        dat_NgaySinh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dat_NgaySinh.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dat_NgaySinhPropertyChange(evt);
            }
        });

        lbl_DiaChi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_DiaChi.setForeground(new java.awt.Color(0, 0, 153));
        lbl_DiaChi.setText("Địa chỉ");

        txa_DiaChi.setColumns(10);
        txa_DiaChi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txa_DiaChi.setRows(2);
        txa_DiaChi.setAutoscrolls(false);
        txa_DiaChi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txa_DiaChiFocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(txa_DiaChi);

        lbl_MatKhauHienTai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_MatKhauHienTai.setForeground(new java.awt.Color(0, 0, 153));
        lbl_MatKhauHienTai.setText("Mật khẩu hiện tại");

        lbl_MatKhauMoi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_MatKhauMoi.setForeground(new java.awt.Color(0, 0, 153));
        lbl_MatKhauMoi.setText("Mật khẩu mới");

        txt_MatKhauHienTai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_MatKhauHienTai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_MatKhauHienTaiFocusLost(evt);
            }
        });
        txt_MatKhauHienTai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_MatKhauHienTaiKeyTyped(evt);
            }
        });

        txt_MatKhauMoi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_MatKhauMoi.setEnabled(false);
        txt_MatKhauMoi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_MatKhauMoiFocusLost(evt);
            }
        });
        txt_MatKhauMoi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_MatKhauMoiKeyTyped(evt);
            }
        });

        btn_Huy.setBackground(new java.awt.Color(153, 0, 0));
        btn_Huy.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btn_Huy.setForeground(new java.awt.Color(255, 255, 255));
        btn_Huy.setText("HUỶ");
        btn_Huy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_HuyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_HuyMouseExited(evt);
            }
        });
        btn_Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HuyActionPerformed(evt);
            }
        });

        btn_CapNhat.setBackground(new java.awt.Color(51, 51, 255));
        btn_CapNhat.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btn_CapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btn_CapNhat.setText("CẬP NHẬT");
        btn_CapNhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_CapNhatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_CapNhatMouseExited(evt);
            }
        });
        btn_CapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_ButtonLayout = new javax.swing.GroupLayout(pnl_Button);
        pnl_Button.setLayout(pnl_ButtonLayout);
        pnl_ButtonLayout.setHorizontalGroup(
            pnl_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Huy, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_CapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_ButtonLayout.setVerticalGroup(
            pnl_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Huy, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btn_CapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        chk_CapNhatMatKhau.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chk_CapNhatMatKhau.setForeground(new java.awt.Color(0, 0, 153));
        chk_CapNhatMatKhau.setText("Cập nhật mật khẩu");
        chk_CapNhatMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chk_CapNhatMatKhauMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbl_GioiTinh)
                                    .addGap(214, 214, 214))
                                .addComponent(lbl_TenDangNhap, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rad_Nam)
                                            .addGap(18, 18, 18)
                                            .addComponent(rad_Nu))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txt_DienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                            .addComponent(txt_TenDangNhap)))
                                    .addComponent(lbl_HoTen)
                                    .addComponent(lbl_DienThoai)
                                    .addComponent(txt_HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_NgaySinh)
                                    .addComponent(dat_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_MatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2)
                                .addComponent(lbl_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_MatKhauHienTai))
                            .addComponent(lbl_MatKhauMoi)
                            .addComponent(lbl_MatKhauHienTai)
                            .addComponent(chk_CapNhatMatKhau))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnl_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_TenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_TenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_DienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_DienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rad_Nam)
                            .addComponent(rad_Nu)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_MatKhauHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_MatKhauHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_MatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dat_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_MatKhauMoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(chk_CapNhatMatKhau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 13, Short.MAX_VALUE)
                .addComponent(pnl_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_HuyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HuyMouseEntered
        // TODO add your handling code here:
        btn_Huy.setBackground(Color.yellow);
        btn_Huy.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btn_Huy.setForeground(Color.blue);
    }//GEN-LAST:event_btn_HuyMouseEntered

    private void btn_HuyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HuyMouseExited
        // TODO add your handling code here:
        btn_Huy.setBackground(new Color(153,0,0));
        btn_Huy.setForeground(Color.white);
    }//GEN-LAST:event_btn_HuyMouseExited

    private void btn_CapNhatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CapNhatMouseEntered
        // TODO add your handling code here:
        btn_CapNhat.setBackground(Color.yellow);
        btn_CapNhat.setForeground(Color.blue);
        btn_CapNhat.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_CapNhatMouseEntered

    private void btn_CapNhatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CapNhatMouseExited
        // TODO add your handling code here:
        btn_CapNhat.setBackground(new Color(51,51,255));
        btn_CapNhat.setForeground(Color.white);
    }//GEN-LAST:event_btn_CapNhatMouseExited

    private void btn_HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HuyActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_HuyActionPerformed

    private void chk_CapNhatMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chk_CapNhatMatKhauMouseClicked
        // TODO add your handling code here:
        checkCapNhat();
    }//GEN-LAST:event_chk_CapNhatMatKhauMouseClicked

    private void btn_CapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapNhatActionPerformed
        // TODO add your handling code here:
        capnhatNguoiDung();
    }//GEN-LAST:event_btn_CapNhatActionPerformed

    private void txt_DienThoaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DienThoaiKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(txt_DienThoai.getText().length() == 11 || !(Character.isDigit(c)) || c == KeyEvent.VK_DELETE || c == KeyEvent.VK_BACK_SPACE){
            evt.consume();
        }
    }//GEN-LAST:event_txt_DienThoaiKeyTyped

    private void txt_DienThoaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_DienThoaiFocusLost
        // TODO add your handling code here:
        if(!checkDienThoai()){
            txt_DienThoai.setBackground(Color.yellow);
        }
        else {
            txt_DienThoai.setBackground(Color.white);
        }
    }//GEN-LAST:event_txt_DienThoaiFocusLost

    private void txt_EmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_EmailFocusLost
        // TODO add your handling code here:
        if(checkEmail()){
            txt_Email.setBackground(Color.WHITE);
        }
        else{
            txt_Email.setBackground(Color.YELLOW);
        }
    }//GEN-LAST:event_txt_EmailFocusLost

    private void dat_NgaySinhPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dat_NgaySinhPropertyChange
        // TODO add your handling code here:
        if(!checkNgaySinh()){
            ((JTextField)dat_NgaySinh.getDateEditor().getUiComponent()).setForeground(Color.red);
            ((JTextField)dat_NgaySinh.getDateEditor().getUiComponent()).setBackground(Color.yellow);
        }
        else {
            ((JTextField)dat_NgaySinh.getDateEditor().getUiComponent()).setForeground(Color.BLACK);
            ((JTextField)dat_NgaySinh.getDateEditor().getUiComponent()).setBackground(Color.white);
        }
    }//GEN-LAST:event_dat_NgaySinhPropertyChange

    private void txa_DiaChiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txa_DiaChiFocusLost
        // TODO add your handling code here:
        if(!checkDiaChi()){
            txa_DiaChi.setBackground(Color.yellow);
        }
        else {
            txa_DiaChi.setBackground(Color.white);
        }
    }//GEN-LAST:event_txa_DiaChiFocusLost

    private void txt_MatKhauHienTaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_MatKhauHienTaiFocusLost
        // TODO add your handling code here:
        if(!checkMatKhau()){
            txt_MatKhauHienTai.setBackground(Color.yellow);
        }
        else {
            txt_MatKhauHienTai.setBackground(Color.white);
        }
    }//GEN-LAST:event_txt_MatKhauHienTaiFocusLost

    private void txt_MatKhauHienTaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_MatKhauHienTaiKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(c == KeyEvent.VK_SPACE){
            evt.consume();
        }
    }//GEN-LAST:event_txt_MatKhauHienTaiKeyTyped

    private void txt_MatKhauMoiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_MatKhauMoiKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(c == KeyEvent.VK_SPACE){
            evt.consume();
        }
    }//GEN-LAST:event_txt_MatKhauMoiKeyTyped

    private void txt_MatKhauMoiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_MatKhauMoiFocusLost
        // TODO add your handling code here:
        if(!checkMatKhauMoi()){
            txt_MatKhauMoi.setBackground(Color.yellow);
        }
        else {
            txt_MatKhauMoi.setBackground(Color.white);
        }
    }//GEN-LAST:event_txt_MatKhauMoiFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongTinTaiKhoanJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongTinTaiKhoanJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongTinTaiKhoanJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongTinTaiKhoanJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongTinTaiKhoanJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btg_GioiTinh;
    private javax.swing.JButton btn_CapNhat;
    private javax.swing.JButton btn_Huy;
    private javax.swing.JCheckBox chk_CapNhatMatKhau;
    private com.toedter.calendar.JDateChooser dat_NgaySinh;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_DiaChi;
    private javax.swing.JLabel lbl_DienThoai;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_GioiTinh;
    private javax.swing.JLabel lbl_HoTen;
    private javax.swing.JLabel lbl_MatKhauHienTai;
    private javax.swing.JLabel lbl_MatKhauMoi;
    private javax.swing.JLabel lbl_NgaySinh;
    private javax.swing.JLabel lbl_TenDangNhap;
    private javax.swing.JPanel pnl_Button;
    private javax.swing.JRadioButton rad_Nam;
    private javax.swing.JRadioButton rad_Nu;
    private javax.swing.JTextArea txa_DiaChi;
    private javax.swing.JTextField txt_DienThoai;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_HoTen;
    private javax.swing.JPasswordField txt_MatKhauHienTai;
    private javax.swing.JPasswordField txt_MatKhauMoi;
    private javax.swing.JTextField txt_TenDangNhap;
    // End of variables declaration//GEN-END:variables
    
    NguoiDungDAO NguoiDungDAO = new NguoiDungDAO();
    
    /*
     * Hàm hiện thông tin người dùng lên các textfield
     */
    void hienThongTin(){
        txt_TenDangNhap.setText(ShareHelper.NguoiDung.getTenDangNhap());
        txt_HoTen.setText(ShareHelper.NguoiDung.getHoTen());
        txt_DienThoai.setText(ShareHelper.NguoiDung.getDienThoai());
        if(ShareHelper.NguoiDung.getGioiTinh()){
            rad_Nam.setSelected(true);
        }
        else {
            rad_Nu.setSelected(true);
        }
        dat_NgaySinh.setDate(ShareHelper.NguoiDung.getNgaySinh());
        txt_Email.setText(ShareHelper.NguoiDung.getEmail());
        txa_DiaChi.setText(ShareHelper.NguoiDung.getDiaChi());
    }
    
    /*
     * Hàm này để enable/disable textfield mật khẩu mới 
           khi check/uncheck vào checkbox cập nhật mật khẩu
     */
    void checkCapNhat(){
        if(chk_CapNhatMatKhau.isSelected()){
            txt_MatKhauMoi.setEnabled(true);
        }
        else {
            txt_MatKhauMoi.setEnabled(false);
        }
    }
    
    /*
     * Hàm cập nhật thông tin người dùng lên database
          sau khi cập nhật thì close frame này, quay về frame bán hàng
     */
    void capnhatNguoiDung(){
        try {
            // kiem loi neu true thi moi cap nhat vao database
            if(kiemLoi()){
                int rs = 0;
                // cap nhat model:
                capnhatModel();
                // kiem tra co cap nhat mat khau moi hay khong
                // neu co thi cap nhat vao model 
                if(chk_CapNhatMatKhau.isSelected()){
                    String MatKhauMoi = new String(txt_MatKhauMoi.getPassword());
                    if(checkMatKhauMoi()){
                        ShareHelper.NguoiDung.setMatKhau(MatKhauMoi);
                        rs = NguoiDungDAO.capnhatNguoiDung(ShareHelper.NguoiDung, true);
                    }
                }
                else {
                    rs = NguoiDungDAO.capnhatNguoiDung(ShareHelper.NguoiDung, false);
                }
                if(rs != 0){
                    DialogHelper.alert(this, "Cập nhật thành công");
                    this.dispose();
                }
                else {
                    DialogHelper.alert(this, "Cập nhật thất bại");
                }
            }
            else {
                DialogHelper.alert(this, "Kiểm tra lại thông tin");
            }
        } catch (Exception e) {
            DialogHelper.alert(this, "Cập nhật thất bại: " + e.toString());
        }
    }
    
    /*
     * Hàm kiểm lỗi trước khi cập nhật người dùng
     */
    boolean kiemLoi(){
        boolean ketqua = true;
        if(!checkEmail()){
            ketqua = false;
        }
        if(!checkDienThoai()){
            ketqua = false;
        }
        if(!checkNgaySinh()){
            ketqua = false;
        }
        if(!checkDiaChi()){
            ketqua = false;
        }
        if(!checkMatKhau()){
            ketqua = false;
        }
        return ketqua;
    }
    
    /*
     * Hàm check email
     */
    boolean checkEmail(){
        String email = txt_Email.getText();
        String pattern = "([A-Za-z0-9-_.]+@[A-Za-z0-9-_]+(?:\\.[A-Za-z0-9]+)+)";
        if(txt_Email.getText().length() <= 0 | (!email.matches(pattern))){
            return false;
        }
        return true;
    }
    
    /*
     * Hàm check ngày sinh: tính đến thời gian hiện tại phải từ 18t trở lên
     */
    boolean checkNgaySinh(){
        if(dat_NgaySinh.getDate() != null){
            Date NgayHienTai = DateHelper.now();
            Date NgaySinh = dat_NgaySinh.getDate();
            long kiemtra = DateHelper.getDateDiff(NgaySinh, NgayHienTai, TimeUnit.DAYS);
            if(kiemtra/365 < 18){
                DialogHelper.alert(this, "Tuổi nhân viên phải từ 18 trở lên");
                return false;
            }
        }
        return true;
    }
    
    /*
     * Hàm check thông tin số điện thoại
           chỉ chứa số, 10 hoặc 11 ký tự
     */
    boolean checkDienThoai(){
        if(txt_DienThoai.getText().length() < 10 || txt_DienThoai.getText().length() > 11){
            return false;
        }
        else
            return true;
    }
    
    /*
     * Hàm check địa chỉ
     */
    boolean checkDiaChi(){
        if(txa_DiaChi.getText().isEmpty()){
            return false;
        }
        else
            return true;
    }
    
    /*
     * Hàm check mật khẩu (tối thiểu 3 ký tự), không có khoảng trắng
     */
    boolean checkMatKhau(){
        String MatKhauHienTai = ShareHelper.NguoiDung.getMatKhau();
        if (txt_MatKhauHienTai.getPassword().length >= 3) {
            if (MatKhauHienTai.equals(new String(txt_MatKhauHienTai.getPassword()))) {
                return true;
            } else {
                return false;
            }
        }
        else
            return false;
    }
    
    /*
     * Hàm check mật khẩu mới (tối thiểu 3 ký tự), không khoảng trắng
     */
    boolean checkMatKhauMoi(){
        if (new String(txt_MatKhauMoi.getPassword()).length() >= 3) {
            return true;
        }
        else
            return false;
    }
    
    /*
     * Hàm cập nhật model
     */
    void capnhatModel(){
        ShareHelper.NguoiDung.setDienThoai(txt_DienThoai.getText());
        ShareHelper.NguoiDung.setGioiTinh(rad_Nam.isSelected());
        ShareHelper.NguoiDung.setNgaySinh(dat_NgaySinh.getDate());
        ShareHelper.NguoiDung.setEmail(txt_Email.getText());
        ShareHelper.NguoiDung.setDiaChi(txa_DiaChi.getText());
    }
}
